name: strembed39
channels:
  - conda-forge
  - defaults
dependencies: # Added pip and python at top to avoid conda giving grumpy warnings
  - pip
  - python=3.9
  - nomkl
  - grakel
  - pythonocc-core=7.7.0
  - pip:
    - wxPython==4.1.1
    - matplotlib
    - networkx
    - nltk
    - scipy
    - xlsxwriter
    - dgl
    - torch
#    - torchvision
#    - torchaudio

prefix: