name: strembed39
channels:
  - conda-forge
  - defaults
dependencies: # Added pip and python at top to avoid conda giving grumpy warnings
  - pip
  - python=3.9
  - grakel
  - pythonocc-core=7.7.0
  - wxpython
  - matplotlib
  - networkx
  - nltk
  - scipy
  - xlsxwriter
  - dglteam::dgl
  - pytorch::cpuonly
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio

prefix: